# Build Bor in a stock Go builder container
FROM golang:1.12-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

# ADD . /bor
# curl for latest bor develop branch
RUN git clone https://github.com/maticnetwork/bor /bor
RUN cd /bor && git checkout develop && make bor

# Pull Bor into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /bor/build/bin/bor /usr/local/bin/

EXPOSE 8545 8546 30303 30303/udp
ARG DATA_DIR
ARG NODE_DIR
ARG INDEX
ARG ADDRESS
ARG HEIMDALL_URL

COPY ./node${INDEX}/bor /root/.bor/
COPY ./node${INDEX}/bor/nodekey /root/.bor/data/bor/
COPY ./node${INDEX}/bor/static-nodes.json /root/.bor/data/
COPY ./entrypoint.sh /entrypoint.sh

ENV DATA_DIR=$DATA_DIR
ENV NODE_DIR=$NODE_DIR
ENV INDEX=$INDEX
ENV ADDRESS=$ADDRESS
ENV HEIMDALL_URL=$HEIMDALL_URL

RUN mkdir -p /root/.bor/data/bor/ 

ENTRYPOINT ["sh", "/entrypoint.sh"]
